stages:
  - test
  - name: release
    if: tag IS present

sudo: false
os: linux

language: python

cache: pip

install:
  - pip install tox

script: tox

jobs:
  include:
    - stage: test
      python: 3.5
      env: TOXENV=py,codecov
    - stage: test
      python: 3.6
      env: TOXENV=py,codecov
    - stage: test
      python: 3.6
      env: TOXENV=lint
    - stage: test
      python: 3.6
      env: TOXENV=docs
    - stage: release
      python: 3.6
      install: skip
      script: skip
      deploy:
        provider: pypi
        user: nmvalera
        distributions: sdist bdist_wheel
        on:
          tags: true
        password:
          secure: FCzrAP3AgTX8RMftJ9shVtzRCZyrlyJD9+EXEqr3VbDCqpjHmlFpYuzPLmeMtIQVCFVNLxQSNGW7rmHCWxqNPJs8/lsTpOxG7DsTzNBIvC4ff1mEfGPCQF55BmZxJpmAxqcdfGAfAh93T+N2Cm8NWzUhkM/w3KKUQtKS5On+PyqGFaTtiNklff5ywQ1PBZUCOfpJuTGsr2kTxazHLy/rKuJYk7R94MHr38tgtcfQ4f91ouBE4Qz+YOwreKkSqLV9pB3rciWv8li25RcHWtUjhMAyb/qr6fCw+DI974BKHBkODIAY9IKCo69NsMUWHzVKrD0oS6SxiOhO5xwmgWeiU4vwNyVwrt2nqgITTuruI9KmDt4P4zPdDD6muPI2MtH68lx9FSZFuY/+GV1aB5imJyI9UsJ2VFiadThjOTPdU+8mDFtPDowi1pwzLmOcaEJGuyBpm9Lt/PwRh7/VUPPTS2s8Q2fiWgMlTSNgNdk7+BShjz3+uHeN3WezD2nD6VktOnkusgG8O8qgcgFa9Fc0jMJUJPjYKz+/CJAjhktFtMusjiRSLcDXdKKejuyE0RrSrEgg4fSRiyFFwtaW3ajr2cTGlUfRR0DLCGfPi3mpjk/wPEaqWuwCWYcuo0wxlzyoIM/wBlwmhwchq7zQGuSWq3lZKkQg9KqKZ2GZH4XAKh0=
